# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6994df10e5cd223ca40f418eac760dd9b09be1904e444b6fefa81089ad2302e20a53158d8668b2aecda881bcac2378e65bdfdba09a456ad6d11d84477f344c5a

test:
  secret_key_base: 957c175fd7e8f559e835e1500c7490bdaf74758eb216db5887d8bcf37d97c607b3d6409401f32303b9fd9176739509559701d9efa1585e24ef02908dffec1ca6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
